import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Generated by `npm run test:coverage`, gitignored — not source.
    "coverage/**",
    // Standalone, dependency-free static site for GitHub Pages — plain
    // classic scripts sharing global scope by design, not part of the
    // Next.js app's TypeScript/React lint rules.
    "demo-site/**",
  ]),
]);

export default eslintConfig;
